### ISSUE TITLE
Email in GitHub ändern

### ISSUE THREAD

**Issue by taitruong** [software-developer-org/bootcamp#10]
- Avatar in Goolge ändern
- in GitHub für Organisation software-developer die Email ändern

Wenn fertig, einfach hier antworten!

**Comment by RagipGashi** [comment]
Done!

**Comment by taitruong** [comment]
@RagipGashi, kannst du sagen, wo man in GitHub das ändern kann? Vlt mit Screenshot?

**Comment by RouvenGonzalez** [comment]
hey ich habs jetzt endlich gefunden :D 
https://github.com/settings/notifications

ganz unten kann man die email für die organisation festlegen 
@taitruong  @RagipGashi

**Comment by taitruong** [comment]
Cool, danke!
@RagipGashi, deadline war Freitag? Bitte erledigen und schließen.

**Comment by RagipGashi** [comment]
@taitruong, habe ich schon erledigt.
