### ISSUE TITLE
new issue Test

### ISSUE THREAD

**Issue by RouvenGonzalez** [software-developer-org/bootcamp#5]
![obiwan](https://user-images.githubusercontent.com/60201852/77410717-9dae9e00-6dbb-11ea-8e00-84af04e2ed7a.jpg)

**Comment by taitruong** [comment]
Star Wars, Episode IV - A new Hope?
@Ragip, was sagt du?

**Comment by RagipGashi** [comment]
*@*taitruong* I hope it too...

**Comment by RagipGashi** [comment]
"*@*taitruong" I hope it too...

**Comment by RagipGashi** [comment]
*@*taitruong I hope it too...

**Comment by RagipGashi** [comment]
@taitruong I use to think positive :)

**Comment by taitruong** [comment]
As soon as you (or me) are in the conversation, you don't need to tag a
person anymore.
@Ragip, unless you really want to say something directly to this person (as
I do in this line) :)!
But keep in mind everybody is in this conversation. So Rouven also gets
this - which is good!

**Comment by taitruong** [comment]
Closing this issue! You can still replay and comment...
